name:                firestarter
version:             0.1.0.0
github:              "githubuser/firestarter"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/firestarter#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- linear
- reflection
- containers
- deepseq
- hashable
- repa
- unordered-containers
- vector
- ad

library:
  source-dirs: src

executables:
  firestarter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firestarter

  firestarter-mesh-exe:
    main:                Main.hs
    source-dirs:         app/firestarterMesh
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - firestarter
    - stm
    - cereal
    - bytestring
